/*
 * SPDX-License-Identifier: MIT-0
 *
 * This file is part of Isobel (https://github.com/jimbovm/isobel).
 */

package io.github.jimbovm.isobel.actor.geography;

import jakarta.validation.constraints.NotNull;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import io.github.jimbovm.isobel.bytecode.geography.ETypeCommand;
import io.github.jimbovm.isobel.common.AreaHeader.Background;

/**
 * This bean represents an instruction to modify the background style
 * of an area on the fly.
 */
@Getter
@Setter
@ToString
@XmlAccessorType(XmlAccessType.NONE)
@XmlRootElement(name = "backgroundModifier")
public final class BackgroundModifier extends GeographyActor {

	/**
	 * Create a new background modifier bean.
	 * 
	 * @param  x          The X position from which the modifier is effective.
	 * @param  background The type of background to render.
	 * 
	 * @return            A new background modifier bean with the supplied
	 *                    parameters.
	 */
	public static BackgroundModifier create(final int x, Background background) {
		var modifier = new BackgroundModifier();
		modifier.setX(x);
		modifier.setBackground(background);
		return modifier;
	}

	@XmlAttribute(name = "background")
	@NotNull
	private Background background = Background.NONE;

	/**
	 * Unparse the bean to its in-game bytecode equivalent.
	 * 
	 * @param newPage Whether to set the new page flag in the generated bytecode.
	 */
	public byte[] unparse(final boolean newPage) {
		return ETypeCommand.unparse(this, newPage);
	}
}
