/*
 * SPDX-License-Identifier: MIT-0
 *
 * This file is part of Isobel (https://github.com/jimbovm/isobel).
 */

package io.github.jimbovm.isobel.actor.geography;

import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import io.github.jimbovm.isobel.actor.Extensible;
import io.github.jimbovm.isobel.actor.YPlaceable;
import io.github.jimbovm.isobel.bytecode.geography.NormalCommand;

/**
 * This bean represents platforms with origin X and Y coordinates which are
 * extensible along some axis.
 * 
 * Depending on the setting of an area's header bits, these objects are
 * rendered either as trees, giant mushrooms or cannons. For trees, the
 * extent controls the width of the platform and the (cosmetic) trunk;
 * mushrooms work in the same way but the stem is always one block wide,
 * and for cannons, the extent controls their height.
 * 
 * @see io.github.jimbovm.isobel.common.AreaHeader
 */
@Getter
@Setter
@ToString
@XmlAccessorType(XmlAccessType.NONE)
@XmlRootElement(name = "extensiblePlatform")
public final class ExtensiblePlatform extends GeographyActor implements YPlaceable, Extensible {

	/**
	 * Create a new extensible platform bean.
	 * 
	 * @param  x      The X position of the platform.
	 * @param  y      The Y position of the platform.
	 * @param  extent The extent of the platform.
	 * 
	 * @return        A new instance of <code>ExtensiblePlatform</code> with the
	 *                given parameters.
	 */
	public static ExtensiblePlatform create(final int x, final int y, final int extent) {
		var platform = new ExtensiblePlatform();
		platform.setX(x);
		platform.setY(y);
		platform.setExtent(extent);
		return platform;
	}

	@XmlAttribute(name = "y")
	@Min(0)
	@Max(0xB)
	private int y;

	@XmlAttribute(name = "extent")
	@Min(0)
	private int extent;

	/**
	 * Unparse the bean to its in-game bytecode equivalent.
	 * 
	 * @param newPage Whether to set the new page flag in the generated bytecode.
	 */
	public byte[] unparse(final boolean newPage) {
		return NormalCommand.unparse(this, newPage);
	}
}
