/*
 * SPDX-License-Identifier: MIT-0
 *
 * This file is part of Isobel (https://github.com/jimbovm/isobel).
 */

package io.github.jimbovm.isobel.actor.geography;

import jakarta.validation.constraints.NotNull;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import io.github.jimbovm.isobel.bytecode.geography.ETypeCommand;
import io.github.jimbovm.isobel.common.AreaHeader.Fill;
import io.github.jimbovm.isobel.common.AreaHeader.Scenery;

/**
 * This bean represents an instruction to modify the terrain fill and/or
 * scenery of an area on the fly.
 */
@Getter
@Setter
@ToString
@XmlAccessorType(XmlAccessType.NONE)
@XmlRootElement(name = "fillSceneryModifier")
public final class FillSceneryModifier extends GeographyActor {

	/**
	 * Create a new fill/scenery modifier bean.
	 * 
	 * @param  x       The X position from which the actor is effective.
	 * @param  fill    The fill type to be rendered.
	 * @param  scenery The scenery type to be rendered.
	 * 
	 * @return         A new instance of <code>FillSceneryModifier</code> with the
	 *                 given parameters.
	 */
	public static FillSceneryModifier create(final int x, Fill fill, Scenery scenery) {
		var modifier = new FillSceneryModifier();
		modifier.setX(x);
		modifier.setFill(fill);
		modifier.setScenery(scenery);
		return modifier;
	}

	@XmlAttribute(name = "fill")
	@NotNull
	private Fill fill = Fill.FILL_2BF_0BC;

	@XmlAttribute(name = "scenery")
	@NotNull
	private Scenery scenery = Scenery.NONE;

	/**
	 * Unparse the bean to its in-game bytecode equivalent.
	 * 
	 * @param newPage Whether to set the new page flag in the generated bytecode.
	 */
	public byte[] unparse(final boolean newPage) {
		return ETypeCommand.unparse(this, newPage);
	}
}
