/*
 * SPDX-License-Identifier: MIT-0
 *
 * This file is part of Isobel (https://github.com/jimbovm/isobel).
 */

package io.github.jimbovm.isobel.actor.geography;

import jakarta.xml.bind.annotation.XmlRootElement;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import io.github.jimbovm.isobel.bytecode.geography.FTypeCommand;

/**
 * This bean represents ropes that extend the full height of the game screen,
 * seen in 2-4 in the original. These ropes are purely cosmetic, and don't
 * do anything.
 */
@Getter
@Setter
@ToString
@XmlRootElement(name = "fullHeightRope")
public final class FullHeightRope extends GeographyActor {

	/**
	 * Create a new full height rope bean.
	 * 
	 * @param  x The X position of the rope.
	 * 
	 * @return   A new full height rope bean with the supplied parameters.
	 */
	public static FullHeightRope create(final int x) {
		var rope = new FullHeightRope();
		rope.setX(x);
		return rope;
	}

	/**
	 * Unparse the bean to its in-game bytecode equivalent.
	 * 
	 * @param newPage Whether to set the new page flag in the generated bytecode.
	 */
	public byte[] unparse(final boolean newPage) {
		return FTypeCommand.unparse(this, newPage);
	}
}
