/*
 * SPDX-License-Identifier: MIT-0
 *
 * This file is part of Isobel (https://github.com/jimbovm/isobel).
 */

package io.github.jimbovm.isobel.actor.geography;

import jakarta.validation.constraints.PositiveOrZero;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import io.github.jimbovm.isobel.actor.Extensible;
import io.github.jimbovm.isobel.bytecode.geography.FTypeCommand;

/**
 * This bean represents the ropes used with scale lifts. Scales (which are
 * spawned by a population command, not a geography command as these ropes
 * are) do not require them to function, but scale lifts will interact with
 * them if they are present.
 * 
 * The extent controls the distance the ropes extend downward from the
 * origin.
 * 
 */
@Getter
@Setter
@ToString
@XmlAccessorType(XmlAccessType.NONE)
@XmlRootElement(name = "scaleRope")
public final class ScaleRopeVertical extends GeographyActor implements Extensible {

	@XmlAttribute(name = "extent")
	@PositiveOrZero
	private int extent;

	/**
	 * Unparse the bean to its in-game bytecode equivalent.
	 * 
	 * @param newPage Whether to set the new page flag in the generated bytecode.
	 */
	public byte[] unparse(final boolean newPage) {
		return FTypeCommand.unparse(this, newPage);
	}
}
