/*
 * SPDX-License-Identifier: MIT-0
 *
 * This file is part of Isobel (https://github.com/jimbovm/isobel).
 */

package io.github.jimbovm.isobel.actor.geography;

import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.PositiveOrZero;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import io.github.jimbovm.isobel.actor.Extensible;
import io.github.jimbovm.isobel.actor.YPlaceable;
import io.github.jimbovm.isobel.bytecode.geography.NormalCommand;

/**
 * This bean represents upright pipes, that is, the familiar kind of
 * warp pipe with the mouth facing straight up. These pipes may be
 * enterable or not and are extensible downward along the Y axis from
 * their initial placement.
 *
 * As with other actors that can be used to exit an area, the
 * destination is not set on the actor itself, but rather by an exit
 * pointer.
 */
@Getter
@Setter
@ToString
@XmlAccessorType(XmlAccessType.NONE)
@XmlRootElement(name = "uprightPipe")
public final class UprightPipe extends GeographyActor implements YPlaceable, Extensible {

	/**
	 * Create a new upright pipe bean.
	 * 
	 * @param  x         The X position of the pipe.
	 * @param  y         The Y position of the pipe.
	 * @param  extent    The downward vertical extent of the pipe.
	 * @param  enterable Whether the pipe can be entered by the player.
	 * 
	 * @return           A new upright pipe bean with the supplied parameters.
	 */
	public static UprightPipe create(final int x, final int y, final int extent, final boolean enterable) {

		var pipe = new UprightPipe();
		pipe.setX(x);
		pipe.setY(y);
		pipe.setExtent(extent);
		pipe.setEnterable(enterable);
		return pipe;
	}

	@XmlAttribute(name = "y")
	@Min(0)
	@Max(0xB)
	private int y;

	@XmlAttribute(name = "extent")
	@PositiveOrZero
	private int extent;

	@XmlAttribute(name = "enterable")
	private boolean enterable;

	/**
	 * Unparse the bean to its in-game bytecode equivalent.
	 * 
	 * @param newPage Whether to set the new page flag in the generated bytecode.
	 */
	public byte[] unparse(final boolean newPage) {
		return NormalCommand.unparse(this, newPage);
	}
}
