/* SPDX-License-Identifier: MIT-0

Copyright 2022 Jimbo Brierley.

Permission is hereby granted, free of charge, to any person obtaining a copy of 
this software and associated documentation files (the "Software"), to deal in 
the Software without restriction, including without limitation the rights to 
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies 
of the Software, and to permit persons to whom the Software is furnished to do 
so.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
SOFTWARE. */

package com.github.jimbovm.isobel.actor.geography;

import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import com.github.jimbovm.isobel.actor.YPlaceable;
import com.github.jimbovm.isobel.bytecode.geography.FTypeCommand;

/**
 * This bean represents angle pipes, as seen in 1-2, 4-2 and underground bonus
 * rooms in the original game, where the mouth of the pipe can be walked into.
 * All these pipes are enterable. They always extend up to the ceiling from
 * their Y position.
 *
 * These are not to be confused with the stubby pipes which resemble "tee"
 * connectors, which are seen in the "interlude" sequence for underground and
 * water levels in the original, and which have fixed extent.
 *
 * As with other actors that can be used to exit an area, the destination is not
 * set on the actor itself, but rather by an exit pointer.
 *
 * @see com.github.jimbovm.isobel.actor.geography.FixedStatic
 * @see com.github.jimbovm.isobel.actor.geography.UprightPipe
 */
@Getter
@Setter
@ToString
@XmlAccessorType(XmlAccessType.NONE)
@XmlRootElement(name = "anglePipe")
public final class AnglePipe extends GeographyActor implements YPlaceable {

	/**
	 * Create a new angle pipe bean.
	 * 
	 * @param x The X position of the pipe.
	 * @param y The Y position of the pipe.
	 * @return A new angle pipe bean with the supplied parameters.
	 */
	public static AnglePipe create(final int x, final int y) {
		var pipe = new AnglePipe();
		pipe.setX(x);
		pipe.setY(y);
		return pipe;
	}

	@XmlAttribute(name = "y")
	@Min(0) @Max(0xB) private int y;

	/**
	 * Unparse the bean to its in-game bytecode equivalent.
	 * 
	 * @param newPage Whether to set the new page flag in the generated bytecode. 
	 */
	public byte[] unparse(final boolean newPage) {
		return FTypeCommand.unparse(this, newPage);
	}
}
