/* SPDX-License-Identifier: MIT-0

Copyright 2022-2024 Jimbo Brierley.

Permission is hereby granted, free of charge, to any person obtaining a copy of 
this software and associated documentation files (the "Software"), to deal in 
the Software without restriction, including without limitation the rights to 
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies 
of the Software, and to permit persons to whom the Software is furnished to do 
so.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
SOFTWARE. */

package com.github.jimbovm.isobel.actor.geography;

import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import com.github.jimbovm.isobel.actor.Extensible;
import com.github.jimbovm.isobel.bytecode.geography.FTypeCommand;

/**
 * This bean represents staircases, which are extensible along the X
 * axis, with each unit of extent adding another step, up until extent
 * 8, which extends the top step to form the familiar end-of-level
 * staircase.
 *
 * Staircases have a fixed Y position: two blocks from the bottom of
 * the screen.
 *
 * Staircases can only be "ascending" (tallest at the right).
 * "Descending" steps (tallest at the left) have to be constructed
 * manually from columns of blocks (1-1 in the original game
 * illustrates this).
 */
@Getter
@Setter
@ToString
@XmlAccessorType(XmlAccessType.NONE)
@XmlRootElement(name = "staircase")
public final class Staircase extends GeographyActor implements Extensible {

	/**
	 * Create a new staircase bean.
	 * 
	 * @param x The X position of the staircase.
	 * @param extent The horizontal extent of the staircase.
	 * @return A new staircase bean with the supplied parameters.
	 */
	public static Staircase create(final int x, final int extent) {
		var staircase = new Staircase();
		staircase.setX(x);
		staircase.setExtent(extent);
		return staircase;
	}
	
	@XmlAttribute(name = "extent")
	@Min(0) @Max(8) private int extent = 0;

	/**
	 * Unparse the bean to its in-game bytecode equivalent.
	 * 
	 * @param newPage Whether to set the new page flag in the generated bytecode. 
	 */
	public byte[] unparse(final boolean newPage) {
		return FTypeCommand.unparse(this, newPage);
	}
}
