/* SPDX-License-Identifier: MIT-0

Copyright 2022-2024 Jimbo Brierley.

Permission is hereby granted, free of charge, to any person obtaining a copy of 
this software and associated documentation files (the "Software"), to deal in 
the Software without restriction, including without limitation the rights to 
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies 
of the Software, and to permit persons to whom the Software is furnished to do 
so.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
SOFTWARE. */

package com.github.jimbovm.isobel.actor.geography;

import com.github.jimbovm.isobel.actor.Extensible;
import com.github.jimbovm.isobel.actor.YPlaceable;
import com.github.jimbovm.isobel.bytecode.geography.NormalCommand;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.PositiveOrZero;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * This bean represents upright pipes, that is, the familiar kind of
 * warp pipe with the mouth facing straight up. These pipes may be
 * enterable or not and are extensible downward along the Y axis from
 * their initial placement.
 *
 * As with other actors that can be used to exit an area, the
 * destination is not set on the actor itself, but rather by an exit
 * pointer.
 */
@Getter
@Setter
@ToString
@XmlAccessorType(XmlAccessType.NONE)
@XmlRootElement(name = "uprightPipe")
public final class UprightPipe extends GeographyActor implements YPlaceable, Extensible {
		
	/**
	 * Create a new upright pipe bean.
	 * 
	 * @param x The X position of the pipe.
	 * @param y The Y position of the pipe.
	 * @param extent The downward vertical extent of the pipe.
	 * @param enterable Whether the pipe can be entered by the player.
	 * @return A new upright pipe bean with the supplied parameters.
	 */
	public static UprightPipe create(
		final int x,
		final int y,
		final int extent,
		final boolean enterable) {

		var pipe = new UprightPipe();
		pipe.setX(x);
		pipe.setY(y);
		pipe.setExtent(extent);
		pipe.setEnterable(enterable);
		return pipe;
	}

	@XmlAttribute(name = "y")
	@Min(0) @Max(0xB) private int y;

	@XmlAttribute(name = "extent")
	@PositiveOrZero private int extent;

	@XmlAttribute(name = "enterable")
	private boolean enterable;

	/**
	 * Unparse the bean to its in-game bytecode equivalent.
	 * 
	 * @param newPage Whether to set the new page flag in the generated bytecode. 
	 */
	public byte[] unparse(final boolean newPage) {
		return NormalCommand.unparse(this, newPage);
	}
}
